### ISSUE TITLE
Suite stops on failure after adding this printer

### ISSUE THREAD

**Issue by poisa** [LimeDeck/phpunit-detailed-printer#1]
I really like this test printer but the only issue I have so far is that as soon as a test fails the whole suite aborts. This behaviour seems to happen only with this printer. 

Is this intentional or is it a bug?

**Comment by rudowastaken** [comment]
Hi, yeah... it's a bug. I will fix it so that this printer is in line with the traditional PHPUnit printer.

**Comment by poisa** [comment]
That would be great, thanks!

**Comment by rudowastaken** [comment]
This has been fixed in 1.2. Thank you for your input!
