### ISSUE TITLE
Add PHPUnit 9 support

### ISSUE THREAD

**Issue by steve-todorov** [LimeDeck/phpunit-detailed-printer#21]
Hi there,

I'm using this dependency and was wondering if there are plans for PHPUnit 9 support?
It looks like in PHPUnit 9 the `PHPUnit\TextUI\ResultPrinter` class has been converted into an `interface` (check sebastianbergmann/phpunit#4024) and there is now a `PHPUnit\TextUI\DefaultResultPrinter`

So the fix to the issue would be simply to change this part: 

https://github.com/LimeDeck/phpunit-detailed-printer/blob/ae5ab59ae406c306b02a7cb8ec95dc99d5e6314c/src/Printer.php#L3-L11

to this:

```php
namespace LimeDeck\Testing;

use PHPUnit\Framework\Test;
use PHPUnit\Framework\Warning;
use PHPUnit\TextUI\DefaultResultPrinter;
use PHPUnit\Util\Test as UtilTest;
use PHPUnit\Framework\AssertionFailedError;

class Printer extends DefaultResultPrinter
{
...
}
```

**Comment by jakubhomoly** [comment]
Hey @steve-todorov, thanks for reporting. Since you've already got this figured out, could you please create a PR? We could release a major version of this to be able to support PHPUnit 9.

Thank you!

**Comment by steve-todorov** [comment]
I've just pushed my changes. Tests are passing on my end but it looks like there's no CI hooked?
